char connectDlg_inline_glade[] = 
"<?xml version='1.0' encoding='UTF-8'?>"
"<!-- Generated with glade 3.22.2 -->"
"<interface>"
"  <requires lib='gtk+' version='3.20'/>"
"  <object class='GtkDialog' id='connect-dlg'>"
"    <property name='width_request'>466</property>"
"    <property name='height_request'>300</property>"
"    <property name='can_focus'>False</property>"
"    <property name='resizable'>False</property>"
"    <property name='modal'>True</property>"
"    <property name='type_hint'>dialog</property>"
"    <child type='titlebar'>"
"      <placeholder/>"
"    </child>"
"    <child internal-child='vbox'>"
"      <object class='GtkBox'>"
"        <property name='can_focus'>False</property>"
"        <property name='orientation'>vertical</property>"
"        <property name='spacing'>2</property>"
"        <child internal-child='action_area'>"
"          <object class='GtkButtonBox'>"
"            <property name='can_focus'>False</property>"
"            <property name='layout_style'>end</property>"
"            <child>"
"              <object class='GtkButton' id='btn-cancel'>"
"                <property name='label' translatable='yes'>Cancel</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='receives_default'>True</property>"
"              </object>"
"              <packing>"
"                <property name='expand'>True</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkButton' id='btn-ok'>"
"                <property name='label' translatable='yes'>Ok</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='receives_default'>True</property>"
"              </object>"
"              <packing>"
"                <property name='expand'>True</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name='expand'>False</property>"
"            <property name='fill'>False</property>"
"            <property name='position'>0</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class='GtkBox'>"
"            <property name='visible'>True</property>"
"            <property name='can_focus'>False</property>"
"            <property name='orientation'>vertical</property>"
"            <child>"
"              <object class='GtkBox'>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='margin_start'>16</property>"
"                <property name='margin_end'>16</property>"
"                <property name='margin_top'>10</property>"
"                <property name='margin_bottom'>10</property>"
"                <child>"
"                  <object class='GtkLabel'>"
"                    <property name='visible'>True</property>"
"                    <property name='can_focus'>False</property>"
"                    <property name='halign'>start</property>"
"                    <property name='xpad'>8</property>"
"                    <property name='label' translatable='yes'>Ardout Host:</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>True</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class='GtkEntry' id='txt-daw-host'>"
"                    <property name='visible'>True</property>"
"                    <property name='can_focus'>True</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>False</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkBox'>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='margin_start'>16</property>"
"                <property name='margin_end'>16</property>"
"                <property name='margin_top'>10</property>"
"                <property name='margin_bottom'>10</property>"
"                <child>"
"                  <object class='GtkLabel'>"
"                    <property name='visible'>True</property>"
"                    <property name='can_focus'>False</property>"
"                    <property name='halign'>start</property>"
"                    <property name='xpad'>8</property>"
"                    <property name='label' translatable='yes'>Ardout Port:</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>True</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class='GtkEntry' id='txt-daw-port'>"
"                    <property name='visible'>True</property>"
"                    <property name='can_focus'>True</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>False</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkBox'>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='margin_start'>16</property>"
"                <property name='margin_end'>16</property>"
"                <property name='margin_top'>10</property>"
"                <property name='margin_bottom'>10</property>"
"                <child>"
"                  <object class='GtkLabel'>"
"                    <property name='visible'>True</property>"
"                    <property name='can_focus'>False</property>"
"                    <property name='halign'>start</property>"
"                    <property name='xpad'>8</property>"
"                    <property name='label' translatable='yes'>Ardout Reply Port:</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>True</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class='GtkEntry' id='txt-daw-reply-port'>"
"                    <property name='visible'>True</property>"
"                    <property name='can_focus'>True</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>False</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>2</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkBox'>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='margin_start'>16</property>"
"                <property name='margin_end'>16</property>"
"                <property name='margin_top'>10</property>"
"                <property name='margin_bottom'>10</property>"
"                <child>"
"                  <object class='GtkLabel'>"
"                    <property name='visible'>True</property>"
"                    <property name='can_focus'>False</property>"
"                    <property name='xpad'>8</property>"
"                    <property name='label' translatable='yes'>Ardout Auto Connect:</property>"
"                    <property name='xalign'>2.2351741291171123e-10</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>True</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class='GtkCheckButton' id='chk-daw-connect'>"
"                    <property name='visible'>True</property>"
"                    <property name='can_focus'>True</property>"
"                    <property name='receives_default'>False</property>"
"                    <property name='draw_indicator'>True</property>"
"                    <child>"
"                      <placeholder/>"
"                    </child>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>True</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>3</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkLabel'>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='label' translatable='yes'> </property>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>4</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkBox'>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='margin_start'>16</property>"
"                <property name='margin_end'>16</property>"
"                <property name='margin_top'>10</property>"
"                <property name='margin_bottom'>10</property>"
"                <child>"
"                  <object class='GtkLabel'>"
"                    <property name='visible'>True</property>"
"                    <property name='can_focus'>False</property>"
"                    <property name='halign'>start</property>"
"                    <property name='xpad'>8</property>"
"                    <property name='label' translatable='yes'>X32 Host:</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>True</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class='GtkEntry' id='txt-x32-host'>"
"                    <property name='visible'>True</property>"
"                    <property name='can_focus'>True</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>False</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>5</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkBox'>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='margin_start'>16</property>"
"                <property name='margin_end'>16</property>"
"                <property name='margin_top'>10</property>"
"                <property name='margin_bottom'>10</property>"
"                <child>"
"                  <object class='GtkLabel'>"
"                    <property name='visible'>True</property>"
"                    <property name='can_focus'>False</property>"
"                    <property name='xpad'>8</property>"
"                    <property name='label' translatable='yes'>X32 Auto Connect:      </property>"
"                    <property name='xalign'>0</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>True</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class='GtkCheckButton' id='chk-x32-connect'>"
"                    <property name='visible'>True</property>"
"                    <property name='can_focus'>True</property>"
"                    <property name='receives_default'>False</property>"
"                    <property name='draw_indicator'>True</property>"
"                    <child>"
"                      <placeholder/>"
"                    </child>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>True</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>6</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name='expand'>False</property>"
"            <property name='fill'>True</property>"
"            <property name='position'>1</property>"
"          </packing>"
"        </child>"
"      </object>"
"    </child>"
"  </object>"
"</interface>"
;
