# Makefile.in generated by automake 1.16.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2018 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/tascamgtk
pkgincludedir = $(includedir)/tascamgtk
pkglibdir = $(libdir)/tascamgtk
pkglibexecdir = $(libexecdir)/tascamgtk
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = autoX32$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(dist_data_DATA) $(noinst_HEADERS) \
	$(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(datadir)" \
	"$(DESTDIR)$(desktopdir)" "$(DESTDIR)$(datadir)" \
	"$(DESTDIR)$(pixmapsdir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_autoX32_OBJECTS = src/autoX32-OMainWndEvents.$(OBJEXT) \
	src/autoX32-OMainWnd.$(OBJEXT) src/autoX32-OOverView.$(OBJEXT) \
	src/autoX32-OscCmd.$(OBJEXT) src/autoX32-OMainWndUI.$(OBJEXT) \
	src/autoX32-OTimeView.$(OBJEXT) \
	src/autoX32-OTracksLayout.$(OBJEXT) \
	src/autoX32-OTrackEditDlg.$(OBJEXT) \
	src/autoX32-OTrackDlg.$(OBJEXT) \
	src/autoX32-OConnectDlg.$(OBJEXT) \
	src/autoX32-OTrackView.$(OBJEXT) \
	src/autoX32-OTrackStore.$(OBJEXT) \
	src/autoX32-OTimeDraw.$(OBJEXT) \
	src/autoX32-OTrackDraw.$(OBJEXT) \
	src/autoX32-OProject.$(OBJEXT) src/autoX32-ODAW.$(OBJEXT) \
	src/autoX32-OX32.$(OBJEXT) src/autoX32-autoX32.$(OBJEXT)
autoX32_OBJECTS = $(am_autoX32_OBJECTS)
am__DEPENDENCIES_1 =
autoX32_DEPENDENCIES = $(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = src/$(DEPDIR)/autoX32-OConnectDlg.Po \
	src/$(DEPDIR)/autoX32-ODAW.Po \
	src/$(DEPDIR)/autoX32-OMainWnd.Po \
	src/$(DEPDIR)/autoX32-OMainWndEvents.Po \
	src/$(DEPDIR)/autoX32-OMainWndUI.Po \
	src/$(DEPDIR)/autoX32-OOverView.Po \
	src/$(DEPDIR)/autoX32-OProject.Po \
	src/$(DEPDIR)/autoX32-OTimeDraw.Po \
	src/$(DEPDIR)/autoX32-OTimeView.Po \
	src/$(DEPDIR)/autoX32-OTrackDlg.Po \
	src/$(DEPDIR)/autoX32-OTrackDraw.Po \
	src/$(DEPDIR)/autoX32-OTrackEditDlg.Po \
	src/$(DEPDIR)/autoX32-OTrackStore.Po \
	src/$(DEPDIR)/autoX32-OTrackView.Po \
	src/$(DEPDIR)/autoX32-OTracksLayout.Po \
	src/$(DEPDIR)/autoX32-OX32.Po src/$(DEPDIR)/autoX32-OscCmd.Po \
	src/$(DEPDIR)/autoX32-autoX32.Po
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(autoX32_SOURCES)
DIST_SOURCES = $(autoX32_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
DATA = $(data_DATA) $(desktop_DATA) $(dist_data_DATA) $(pixmaps_DATA)
HEADERS = $(noinst_HEADERS)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/config.h.in compile \
	depcomp install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/onkel/Projects/github/autoX32/missing aclocal-1.16
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /home/onkel/Projects/github/autoX32/missing autoconf
AUTOHEADER = ${SHELL} /home/onkel/Projects/github/autoX32/missing autoheader
AUTOMAKE = ${SHELL} /home/onkel/Projects/github/autoX32/missing automake-1.16
AWK = gawk
CC = /usr/bin/gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g3 -gdwarf-2
CPP = /usr/bin/gcc -E
CPPFLAGS = 
CXX = /usr/bin/g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g3 -gdwarf-2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
GLIB_COMPILE_SCHEMAS = /usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas
GREP = /usr/bin/grep
GSETTINGS_DISABLE_SCHEMAS_COMPILE = 
GTKMM3_CFLAGS = -pthread -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
GTKMM3_LIBS = -lgtkmm-3.0 -latkmm-1.6 -lgdkmm-3.0 -lgiomm-2.4 -lpangomm-1.4 -lglibmm-2.4 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lgio-2.0 -lcairomm-1.0 -lcairo -lsigc-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LO_CFLAGS = 
LO_LIBS = -llo -lpthread
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/onkel/Projects/github/autoX32/missing makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = tascamgtk
PACKAGE_BUGREPORT = onkel@paraair.de
PACKAGE_NAME = tascamgtk
PACKAGE_STRING = tascamgtk 0.4
PACKAGE_TARNAME = tascamgtk
PACKAGE_URL = 
PACKAGE_VERSION = 0.4
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 0.4
XML2_CFLAGS = -I/usr/include/libxml++-2.6 -I/usr/lib/x86_64-linux-gnu/libxml++-2.6/include -I/usr/include/libxml2 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include
XML2_LIBS = -lxml++-2.6 -lxml2 -lglibmm-2.4 -lgobject-2.0 -lglib-2.0 -lsigc-2.0
abs_builddir = /home/onkel/Projects/github/autoX32
abs_srcdir = /home/onkel/Projects/github/autoX32
abs_top_builddir = /home/onkel/Projects/github/autoX32
abs_top_srcdir = /home/onkel/Projects/github/autoX32
ac_ct_CC = /usr/bin/gcc
ac_ct_CXX = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = $(prefix)/share/autoX32/
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
gsettingsschemadir = ${datarootdir}/glib-2.0/schemas
host_alias = 
htmldir = ${docdir}
includedir = $(prefix)/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/onkel/Projects/github/autoX32/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
desktopdir = $(prefix)/share/applications
pixmapsdir = $(prefix)/share/pixmaps
autoX32kdir = src
autoX32_SOURCES = \
    src/OMainWndEvents.cpp \
    src/OMainWnd.cpp \
    src/OOverView.cpp \
    src/OscCmd.cpp \
    src/OMainWndUI.cpp \
    src/OTimeView.cpp \
    src/OTracksLayout.cpp \
    src/OTrackEditDlg.cpp \
    src/OTrackDlg.cpp \
    src/OConnectDlg.cpp \
    src/OTrackView.cpp \
    src/OTrackStore.cpp \
    src/OTimeDraw.cpp \
    src/OTrackDraw.cpp \
    src/OProject.cpp \
    src/ODAW.cpp \
    src/OX32.cpp \
src/autoX32.cpp

noinst_HEADERS = \
    src/OTimeDraw.h \
    src/OMainWnd.h \
    src/OOverView.h \
    src/OTrackDraw.h \
    src/OTimeView.h \
    src/OTrackStore.h \
    src/ODAW.h \
    src/OscCmd.h \
    src/OProject.h \
    src/OTrackEditDlg.h \
    src/OTrackDlg.h \
    src/OConnectDlg.h \
    src/OX32.h

AM_CFLAGS = -O2
#AM_CFLAGS = -g3 -O0
AM_CXXFLAGS = -O2
#AM_CXXFLAGS = -g3 -O0
data_DATA = data/media/autoX32.png
dist_data_DATA = data/media/autoX32.png
desktop_DATA = data/autoX32.desktop
pixmaps_DATA = data/media/autoX32.png
autoX32_CPPFLAGS = -std=c++11 ${GTK3_CFLAGS} ${GTKMM3_CFLAGS} ${XML2_CFLAGS} ${LO_CFLAGS} -DPKGDATADIR='"$(datadir)"' 
autoX32_LDADD = ${GTKMM3_LIBS} ${XML2_LIBS} ${LO_LIBS} -lpthread
gsettings_SCHEMAS = de.paraair.autoX32.gschema.xml
EXTRA_DIST = $(gsettings_SCHEMAS) \
	     $(pixmaps_DATA) \
	     $(desktop_DATA)

all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OMainWndEvents.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OMainWnd.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OOverView.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OscCmd.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OMainWndUI.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OTimeView.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OTracksLayout.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OTrackEditDlg.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OTrackDlg.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OConnectDlg.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OTrackView.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OTrackStore.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OTimeDraw.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OTrackDraw.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OProject.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-ODAW.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-OX32.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/autoX32-autoX32.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

autoX32$(EXEEXT): $(autoX32_OBJECTS) $(autoX32_DEPENDENCIES) $(EXTRA_autoX32_DEPENDENCIES) 
	@rm -f autoX32$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(autoX32_OBJECTS) $(autoX32_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/autoX32-OConnectDlg.Po # am--include-marker
include src/$(DEPDIR)/autoX32-ODAW.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OMainWnd.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OMainWndEvents.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OMainWndUI.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OOverView.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OProject.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OTimeDraw.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OTimeView.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OTrackDlg.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OTrackDraw.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OTrackEditDlg.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OTrackStore.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OTrackView.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OTracksLayout.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OX32.Po # am--include-marker
include src/$(DEPDIR)/autoX32-OscCmd.Po # am--include-marker
include src/$(DEPDIR)/autoX32-autoX32.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

src/autoX32-OMainWndEvents.o: src/OMainWndEvents.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OMainWndEvents.o -MD -MP -MF src/$(DEPDIR)/autoX32-OMainWndEvents.Tpo -c -o src/autoX32-OMainWndEvents.o `test -f 'src/OMainWndEvents.cpp' || echo '$(srcdir)/'`src/OMainWndEvents.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OMainWndEvents.Tpo src/$(DEPDIR)/autoX32-OMainWndEvents.Po
#	$(AM_V_CXX)source='src/OMainWndEvents.cpp' object='src/autoX32-OMainWndEvents.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OMainWndEvents.o `test -f 'src/OMainWndEvents.cpp' || echo '$(srcdir)/'`src/OMainWndEvents.cpp

src/autoX32-OMainWndEvents.obj: src/OMainWndEvents.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OMainWndEvents.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OMainWndEvents.Tpo -c -o src/autoX32-OMainWndEvents.obj `if test -f 'src/OMainWndEvents.cpp'; then $(CYGPATH_W) 'src/OMainWndEvents.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OMainWndEvents.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OMainWndEvents.Tpo src/$(DEPDIR)/autoX32-OMainWndEvents.Po
#	$(AM_V_CXX)source='src/OMainWndEvents.cpp' object='src/autoX32-OMainWndEvents.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OMainWndEvents.obj `if test -f 'src/OMainWndEvents.cpp'; then $(CYGPATH_W) 'src/OMainWndEvents.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OMainWndEvents.cpp'; fi`

src/autoX32-OMainWnd.o: src/OMainWnd.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OMainWnd.o -MD -MP -MF src/$(DEPDIR)/autoX32-OMainWnd.Tpo -c -o src/autoX32-OMainWnd.o `test -f 'src/OMainWnd.cpp' || echo '$(srcdir)/'`src/OMainWnd.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OMainWnd.Tpo src/$(DEPDIR)/autoX32-OMainWnd.Po
#	$(AM_V_CXX)source='src/OMainWnd.cpp' object='src/autoX32-OMainWnd.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OMainWnd.o `test -f 'src/OMainWnd.cpp' || echo '$(srcdir)/'`src/OMainWnd.cpp

src/autoX32-OMainWnd.obj: src/OMainWnd.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OMainWnd.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OMainWnd.Tpo -c -o src/autoX32-OMainWnd.obj `if test -f 'src/OMainWnd.cpp'; then $(CYGPATH_W) 'src/OMainWnd.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OMainWnd.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OMainWnd.Tpo src/$(DEPDIR)/autoX32-OMainWnd.Po
#	$(AM_V_CXX)source='src/OMainWnd.cpp' object='src/autoX32-OMainWnd.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OMainWnd.obj `if test -f 'src/OMainWnd.cpp'; then $(CYGPATH_W) 'src/OMainWnd.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OMainWnd.cpp'; fi`

src/autoX32-OOverView.o: src/OOverView.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OOverView.o -MD -MP -MF src/$(DEPDIR)/autoX32-OOverView.Tpo -c -o src/autoX32-OOverView.o `test -f 'src/OOverView.cpp' || echo '$(srcdir)/'`src/OOverView.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OOverView.Tpo src/$(DEPDIR)/autoX32-OOverView.Po
#	$(AM_V_CXX)source='src/OOverView.cpp' object='src/autoX32-OOverView.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OOverView.o `test -f 'src/OOverView.cpp' || echo '$(srcdir)/'`src/OOverView.cpp

src/autoX32-OOverView.obj: src/OOverView.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OOverView.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OOverView.Tpo -c -o src/autoX32-OOverView.obj `if test -f 'src/OOverView.cpp'; then $(CYGPATH_W) 'src/OOverView.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OOverView.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OOverView.Tpo src/$(DEPDIR)/autoX32-OOverView.Po
#	$(AM_V_CXX)source='src/OOverView.cpp' object='src/autoX32-OOverView.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OOverView.obj `if test -f 'src/OOverView.cpp'; then $(CYGPATH_W) 'src/OOverView.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OOverView.cpp'; fi`

src/autoX32-OscCmd.o: src/OscCmd.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OscCmd.o -MD -MP -MF src/$(DEPDIR)/autoX32-OscCmd.Tpo -c -o src/autoX32-OscCmd.o `test -f 'src/OscCmd.cpp' || echo '$(srcdir)/'`src/OscCmd.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OscCmd.Tpo src/$(DEPDIR)/autoX32-OscCmd.Po
#	$(AM_V_CXX)source='src/OscCmd.cpp' object='src/autoX32-OscCmd.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OscCmd.o `test -f 'src/OscCmd.cpp' || echo '$(srcdir)/'`src/OscCmd.cpp

src/autoX32-OscCmd.obj: src/OscCmd.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OscCmd.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OscCmd.Tpo -c -o src/autoX32-OscCmd.obj `if test -f 'src/OscCmd.cpp'; then $(CYGPATH_W) 'src/OscCmd.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OscCmd.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OscCmd.Tpo src/$(DEPDIR)/autoX32-OscCmd.Po
#	$(AM_V_CXX)source='src/OscCmd.cpp' object='src/autoX32-OscCmd.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OscCmd.obj `if test -f 'src/OscCmd.cpp'; then $(CYGPATH_W) 'src/OscCmd.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OscCmd.cpp'; fi`

src/autoX32-OMainWndUI.o: src/OMainWndUI.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OMainWndUI.o -MD -MP -MF src/$(DEPDIR)/autoX32-OMainWndUI.Tpo -c -o src/autoX32-OMainWndUI.o `test -f 'src/OMainWndUI.cpp' || echo '$(srcdir)/'`src/OMainWndUI.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OMainWndUI.Tpo src/$(DEPDIR)/autoX32-OMainWndUI.Po
#	$(AM_V_CXX)source='src/OMainWndUI.cpp' object='src/autoX32-OMainWndUI.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OMainWndUI.o `test -f 'src/OMainWndUI.cpp' || echo '$(srcdir)/'`src/OMainWndUI.cpp

src/autoX32-OMainWndUI.obj: src/OMainWndUI.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OMainWndUI.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OMainWndUI.Tpo -c -o src/autoX32-OMainWndUI.obj `if test -f 'src/OMainWndUI.cpp'; then $(CYGPATH_W) 'src/OMainWndUI.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OMainWndUI.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OMainWndUI.Tpo src/$(DEPDIR)/autoX32-OMainWndUI.Po
#	$(AM_V_CXX)source='src/OMainWndUI.cpp' object='src/autoX32-OMainWndUI.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OMainWndUI.obj `if test -f 'src/OMainWndUI.cpp'; then $(CYGPATH_W) 'src/OMainWndUI.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OMainWndUI.cpp'; fi`

src/autoX32-OTimeView.o: src/OTimeView.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTimeView.o -MD -MP -MF src/$(DEPDIR)/autoX32-OTimeView.Tpo -c -o src/autoX32-OTimeView.o `test -f 'src/OTimeView.cpp' || echo '$(srcdir)/'`src/OTimeView.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTimeView.Tpo src/$(DEPDIR)/autoX32-OTimeView.Po
#	$(AM_V_CXX)source='src/OTimeView.cpp' object='src/autoX32-OTimeView.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTimeView.o `test -f 'src/OTimeView.cpp' || echo '$(srcdir)/'`src/OTimeView.cpp

src/autoX32-OTimeView.obj: src/OTimeView.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTimeView.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OTimeView.Tpo -c -o src/autoX32-OTimeView.obj `if test -f 'src/OTimeView.cpp'; then $(CYGPATH_W) 'src/OTimeView.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTimeView.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTimeView.Tpo src/$(DEPDIR)/autoX32-OTimeView.Po
#	$(AM_V_CXX)source='src/OTimeView.cpp' object='src/autoX32-OTimeView.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTimeView.obj `if test -f 'src/OTimeView.cpp'; then $(CYGPATH_W) 'src/OTimeView.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTimeView.cpp'; fi`

src/autoX32-OTracksLayout.o: src/OTracksLayout.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTracksLayout.o -MD -MP -MF src/$(DEPDIR)/autoX32-OTracksLayout.Tpo -c -o src/autoX32-OTracksLayout.o `test -f 'src/OTracksLayout.cpp' || echo '$(srcdir)/'`src/OTracksLayout.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTracksLayout.Tpo src/$(DEPDIR)/autoX32-OTracksLayout.Po
#	$(AM_V_CXX)source='src/OTracksLayout.cpp' object='src/autoX32-OTracksLayout.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTracksLayout.o `test -f 'src/OTracksLayout.cpp' || echo '$(srcdir)/'`src/OTracksLayout.cpp

src/autoX32-OTracksLayout.obj: src/OTracksLayout.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTracksLayout.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OTracksLayout.Tpo -c -o src/autoX32-OTracksLayout.obj `if test -f 'src/OTracksLayout.cpp'; then $(CYGPATH_W) 'src/OTracksLayout.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTracksLayout.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTracksLayout.Tpo src/$(DEPDIR)/autoX32-OTracksLayout.Po
#	$(AM_V_CXX)source='src/OTracksLayout.cpp' object='src/autoX32-OTracksLayout.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTracksLayout.obj `if test -f 'src/OTracksLayout.cpp'; then $(CYGPATH_W) 'src/OTracksLayout.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTracksLayout.cpp'; fi`

src/autoX32-OTrackEditDlg.o: src/OTrackEditDlg.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTrackEditDlg.o -MD -MP -MF src/$(DEPDIR)/autoX32-OTrackEditDlg.Tpo -c -o src/autoX32-OTrackEditDlg.o `test -f 'src/OTrackEditDlg.cpp' || echo '$(srcdir)/'`src/OTrackEditDlg.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTrackEditDlg.Tpo src/$(DEPDIR)/autoX32-OTrackEditDlg.Po
#	$(AM_V_CXX)source='src/OTrackEditDlg.cpp' object='src/autoX32-OTrackEditDlg.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTrackEditDlg.o `test -f 'src/OTrackEditDlg.cpp' || echo '$(srcdir)/'`src/OTrackEditDlg.cpp

src/autoX32-OTrackEditDlg.obj: src/OTrackEditDlg.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTrackEditDlg.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OTrackEditDlg.Tpo -c -o src/autoX32-OTrackEditDlg.obj `if test -f 'src/OTrackEditDlg.cpp'; then $(CYGPATH_W) 'src/OTrackEditDlg.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTrackEditDlg.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTrackEditDlg.Tpo src/$(DEPDIR)/autoX32-OTrackEditDlg.Po
#	$(AM_V_CXX)source='src/OTrackEditDlg.cpp' object='src/autoX32-OTrackEditDlg.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTrackEditDlg.obj `if test -f 'src/OTrackEditDlg.cpp'; then $(CYGPATH_W) 'src/OTrackEditDlg.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTrackEditDlg.cpp'; fi`

src/autoX32-OTrackDlg.o: src/OTrackDlg.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTrackDlg.o -MD -MP -MF src/$(DEPDIR)/autoX32-OTrackDlg.Tpo -c -o src/autoX32-OTrackDlg.o `test -f 'src/OTrackDlg.cpp' || echo '$(srcdir)/'`src/OTrackDlg.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTrackDlg.Tpo src/$(DEPDIR)/autoX32-OTrackDlg.Po
#	$(AM_V_CXX)source='src/OTrackDlg.cpp' object='src/autoX32-OTrackDlg.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTrackDlg.o `test -f 'src/OTrackDlg.cpp' || echo '$(srcdir)/'`src/OTrackDlg.cpp

src/autoX32-OTrackDlg.obj: src/OTrackDlg.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTrackDlg.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OTrackDlg.Tpo -c -o src/autoX32-OTrackDlg.obj `if test -f 'src/OTrackDlg.cpp'; then $(CYGPATH_W) 'src/OTrackDlg.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTrackDlg.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTrackDlg.Tpo src/$(DEPDIR)/autoX32-OTrackDlg.Po
#	$(AM_V_CXX)source='src/OTrackDlg.cpp' object='src/autoX32-OTrackDlg.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTrackDlg.obj `if test -f 'src/OTrackDlg.cpp'; then $(CYGPATH_W) 'src/OTrackDlg.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTrackDlg.cpp'; fi`

src/autoX32-OConnectDlg.o: src/OConnectDlg.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OConnectDlg.o -MD -MP -MF src/$(DEPDIR)/autoX32-OConnectDlg.Tpo -c -o src/autoX32-OConnectDlg.o `test -f 'src/OConnectDlg.cpp' || echo '$(srcdir)/'`src/OConnectDlg.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OConnectDlg.Tpo src/$(DEPDIR)/autoX32-OConnectDlg.Po
#	$(AM_V_CXX)source='src/OConnectDlg.cpp' object='src/autoX32-OConnectDlg.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OConnectDlg.o `test -f 'src/OConnectDlg.cpp' || echo '$(srcdir)/'`src/OConnectDlg.cpp

src/autoX32-OConnectDlg.obj: src/OConnectDlg.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OConnectDlg.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OConnectDlg.Tpo -c -o src/autoX32-OConnectDlg.obj `if test -f 'src/OConnectDlg.cpp'; then $(CYGPATH_W) 'src/OConnectDlg.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OConnectDlg.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OConnectDlg.Tpo src/$(DEPDIR)/autoX32-OConnectDlg.Po
#	$(AM_V_CXX)source='src/OConnectDlg.cpp' object='src/autoX32-OConnectDlg.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OConnectDlg.obj `if test -f 'src/OConnectDlg.cpp'; then $(CYGPATH_W) 'src/OConnectDlg.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OConnectDlg.cpp'; fi`

src/autoX32-OTrackView.o: src/OTrackView.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTrackView.o -MD -MP -MF src/$(DEPDIR)/autoX32-OTrackView.Tpo -c -o src/autoX32-OTrackView.o `test -f 'src/OTrackView.cpp' || echo '$(srcdir)/'`src/OTrackView.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTrackView.Tpo src/$(DEPDIR)/autoX32-OTrackView.Po
#	$(AM_V_CXX)source='src/OTrackView.cpp' object='src/autoX32-OTrackView.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTrackView.o `test -f 'src/OTrackView.cpp' || echo '$(srcdir)/'`src/OTrackView.cpp

src/autoX32-OTrackView.obj: src/OTrackView.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTrackView.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OTrackView.Tpo -c -o src/autoX32-OTrackView.obj `if test -f 'src/OTrackView.cpp'; then $(CYGPATH_W) 'src/OTrackView.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTrackView.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTrackView.Tpo src/$(DEPDIR)/autoX32-OTrackView.Po
#	$(AM_V_CXX)source='src/OTrackView.cpp' object='src/autoX32-OTrackView.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTrackView.obj `if test -f 'src/OTrackView.cpp'; then $(CYGPATH_W) 'src/OTrackView.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTrackView.cpp'; fi`

src/autoX32-OTrackStore.o: src/OTrackStore.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTrackStore.o -MD -MP -MF src/$(DEPDIR)/autoX32-OTrackStore.Tpo -c -o src/autoX32-OTrackStore.o `test -f 'src/OTrackStore.cpp' || echo '$(srcdir)/'`src/OTrackStore.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTrackStore.Tpo src/$(DEPDIR)/autoX32-OTrackStore.Po
#	$(AM_V_CXX)source='src/OTrackStore.cpp' object='src/autoX32-OTrackStore.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTrackStore.o `test -f 'src/OTrackStore.cpp' || echo '$(srcdir)/'`src/OTrackStore.cpp

src/autoX32-OTrackStore.obj: src/OTrackStore.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTrackStore.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OTrackStore.Tpo -c -o src/autoX32-OTrackStore.obj `if test -f 'src/OTrackStore.cpp'; then $(CYGPATH_W) 'src/OTrackStore.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTrackStore.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTrackStore.Tpo src/$(DEPDIR)/autoX32-OTrackStore.Po
#	$(AM_V_CXX)source='src/OTrackStore.cpp' object='src/autoX32-OTrackStore.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTrackStore.obj `if test -f 'src/OTrackStore.cpp'; then $(CYGPATH_W) 'src/OTrackStore.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTrackStore.cpp'; fi`

src/autoX32-OTimeDraw.o: src/OTimeDraw.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTimeDraw.o -MD -MP -MF src/$(DEPDIR)/autoX32-OTimeDraw.Tpo -c -o src/autoX32-OTimeDraw.o `test -f 'src/OTimeDraw.cpp' || echo '$(srcdir)/'`src/OTimeDraw.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTimeDraw.Tpo src/$(DEPDIR)/autoX32-OTimeDraw.Po
#	$(AM_V_CXX)source='src/OTimeDraw.cpp' object='src/autoX32-OTimeDraw.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTimeDraw.o `test -f 'src/OTimeDraw.cpp' || echo '$(srcdir)/'`src/OTimeDraw.cpp

src/autoX32-OTimeDraw.obj: src/OTimeDraw.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTimeDraw.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OTimeDraw.Tpo -c -o src/autoX32-OTimeDraw.obj `if test -f 'src/OTimeDraw.cpp'; then $(CYGPATH_W) 'src/OTimeDraw.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTimeDraw.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTimeDraw.Tpo src/$(DEPDIR)/autoX32-OTimeDraw.Po
#	$(AM_V_CXX)source='src/OTimeDraw.cpp' object='src/autoX32-OTimeDraw.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTimeDraw.obj `if test -f 'src/OTimeDraw.cpp'; then $(CYGPATH_W) 'src/OTimeDraw.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTimeDraw.cpp'; fi`

src/autoX32-OTrackDraw.o: src/OTrackDraw.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTrackDraw.o -MD -MP -MF src/$(DEPDIR)/autoX32-OTrackDraw.Tpo -c -o src/autoX32-OTrackDraw.o `test -f 'src/OTrackDraw.cpp' || echo '$(srcdir)/'`src/OTrackDraw.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTrackDraw.Tpo src/$(DEPDIR)/autoX32-OTrackDraw.Po
#	$(AM_V_CXX)source='src/OTrackDraw.cpp' object='src/autoX32-OTrackDraw.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTrackDraw.o `test -f 'src/OTrackDraw.cpp' || echo '$(srcdir)/'`src/OTrackDraw.cpp

src/autoX32-OTrackDraw.obj: src/OTrackDraw.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OTrackDraw.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OTrackDraw.Tpo -c -o src/autoX32-OTrackDraw.obj `if test -f 'src/OTrackDraw.cpp'; then $(CYGPATH_W) 'src/OTrackDraw.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTrackDraw.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OTrackDraw.Tpo src/$(DEPDIR)/autoX32-OTrackDraw.Po
#	$(AM_V_CXX)source='src/OTrackDraw.cpp' object='src/autoX32-OTrackDraw.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OTrackDraw.obj `if test -f 'src/OTrackDraw.cpp'; then $(CYGPATH_W) 'src/OTrackDraw.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OTrackDraw.cpp'; fi`

src/autoX32-OProject.o: src/OProject.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OProject.o -MD -MP -MF src/$(DEPDIR)/autoX32-OProject.Tpo -c -o src/autoX32-OProject.o `test -f 'src/OProject.cpp' || echo '$(srcdir)/'`src/OProject.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OProject.Tpo src/$(DEPDIR)/autoX32-OProject.Po
#	$(AM_V_CXX)source='src/OProject.cpp' object='src/autoX32-OProject.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OProject.o `test -f 'src/OProject.cpp' || echo '$(srcdir)/'`src/OProject.cpp

src/autoX32-OProject.obj: src/OProject.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OProject.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OProject.Tpo -c -o src/autoX32-OProject.obj `if test -f 'src/OProject.cpp'; then $(CYGPATH_W) 'src/OProject.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OProject.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OProject.Tpo src/$(DEPDIR)/autoX32-OProject.Po
#	$(AM_V_CXX)source='src/OProject.cpp' object='src/autoX32-OProject.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OProject.obj `if test -f 'src/OProject.cpp'; then $(CYGPATH_W) 'src/OProject.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OProject.cpp'; fi`

src/autoX32-ODAW.o: src/ODAW.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-ODAW.o -MD -MP -MF src/$(DEPDIR)/autoX32-ODAW.Tpo -c -o src/autoX32-ODAW.o `test -f 'src/ODAW.cpp' || echo '$(srcdir)/'`src/ODAW.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-ODAW.Tpo src/$(DEPDIR)/autoX32-ODAW.Po
#	$(AM_V_CXX)source='src/ODAW.cpp' object='src/autoX32-ODAW.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-ODAW.o `test -f 'src/ODAW.cpp' || echo '$(srcdir)/'`src/ODAW.cpp

src/autoX32-ODAW.obj: src/ODAW.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-ODAW.obj -MD -MP -MF src/$(DEPDIR)/autoX32-ODAW.Tpo -c -o src/autoX32-ODAW.obj `if test -f 'src/ODAW.cpp'; then $(CYGPATH_W) 'src/ODAW.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ODAW.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-ODAW.Tpo src/$(DEPDIR)/autoX32-ODAW.Po
#	$(AM_V_CXX)source='src/ODAW.cpp' object='src/autoX32-ODAW.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-ODAW.obj `if test -f 'src/ODAW.cpp'; then $(CYGPATH_W) 'src/ODAW.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ODAW.cpp'; fi`

src/autoX32-OX32.o: src/OX32.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OX32.o -MD -MP -MF src/$(DEPDIR)/autoX32-OX32.Tpo -c -o src/autoX32-OX32.o `test -f 'src/OX32.cpp' || echo '$(srcdir)/'`src/OX32.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OX32.Tpo src/$(DEPDIR)/autoX32-OX32.Po
#	$(AM_V_CXX)source='src/OX32.cpp' object='src/autoX32-OX32.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OX32.o `test -f 'src/OX32.cpp' || echo '$(srcdir)/'`src/OX32.cpp

src/autoX32-OX32.obj: src/OX32.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-OX32.obj -MD -MP -MF src/$(DEPDIR)/autoX32-OX32.Tpo -c -o src/autoX32-OX32.obj `if test -f 'src/OX32.cpp'; then $(CYGPATH_W) 'src/OX32.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OX32.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-OX32.Tpo src/$(DEPDIR)/autoX32-OX32.Po
#	$(AM_V_CXX)source='src/OX32.cpp' object='src/autoX32-OX32.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-OX32.obj `if test -f 'src/OX32.cpp'; then $(CYGPATH_W) 'src/OX32.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OX32.cpp'; fi`

src/autoX32-autoX32.o: src/autoX32.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-autoX32.o -MD -MP -MF src/$(DEPDIR)/autoX32-autoX32.Tpo -c -o src/autoX32-autoX32.o `test -f 'src/autoX32.cpp' || echo '$(srcdir)/'`src/autoX32.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-autoX32.Tpo src/$(DEPDIR)/autoX32-autoX32.Po
#	$(AM_V_CXX)source='src/autoX32.cpp' object='src/autoX32-autoX32.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-autoX32.o `test -f 'src/autoX32.cpp' || echo '$(srcdir)/'`src/autoX32.cpp

src/autoX32-autoX32.obj: src/autoX32.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/autoX32-autoX32.obj -MD -MP -MF src/$(DEPDIR)/autoX32-autoX32.Tpo -c -o src/autoX32-autoX32.obj `if test -f 'src/autoX32.cpp'; then $(CYGPATH_W) 'src/autoX32.cpp'; else $(CYGPATH_W) '$(srcdir)/src/autoX32.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/autoX32-autoX32.Tpo src/$(DEPDIR)/autoX32-autoX32.Po
#	$(AM_V_CXX)source='src/autoX32.cpp' object='src/autoX32-autoX32.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(autoX32_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/autoX32-autoX32.obj `if test -f 'src/autoX32.cpp'; then $(CYGPATH_W) 'src/autoX32.cpp'; else $(CYGPATH_W) '$(srcdir)/src/autoX32.cpp'; fi`
install-dataDATA: $(data_DATA)
	@$(NORMAL_INSTALL)
	@list='$(data_DATA)'; test -n "$(datadir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(datadir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(datadir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(datadir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(datadir)" || exit $$?; \
	done

uninstall-dataDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(data_DATA)'; test -n "$(datadir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(datadir)'; $(am__uninstall_files_from_dir)
install-desktopDATA: $(desktop_DATA)
	@$(NORMAL_INSTALL)
	@list='$(desktop_DATA)'; test -n "$(desktopdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(desktopdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(desktopdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(desktopdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(desktopdir)" || exit $$?; \
	done

uninstall-desktopDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(desktop_DATA)'; test -n "$(desktopdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(desktopdir)'; $(am__uninstall_files_from_dir)
install-dist_dataDATA: $(dist_data_DATA)
	@$(NORMAL_INSTALL)
	@list='$(dist_data_DATA)'; test -n "$(datadir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(datadir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(datadir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(datadir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(datadir)" || exit $$?; \
	done

uninstall-dist_dataDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_data_DATA)'; test -n "$(datadir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(datadir)'; $(am__uninstall_files_from_dir)
install-pixmapsDATA: $(pixmaps_DATA)
	@$(NORMAL_INSTALL)
	@list='$(pixmaps_DATA)'; test -n "$(pixmapsdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(pixmapsdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(pixmapsdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pixmapsdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pixmapsdir)" || exit $$?; \
	done

uninstall-pixmapsDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pixmaps_DATA)'; test -n "$(pixmapsdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pixmapsdir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(DATA) $(HEADERS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(datadir)" "$(DESTDIR)$(desktopdir)" "$(DESTDIR)$(datadir)" "$(DESTDIR)$(pixmapsdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
		-rm -f src/$(DEPDIR)/autoX32-OConnectDlg.Po
	-rm -f src/$(DEPDIR)/autoX32-ODAW.Po
	-rm -f src/$(DEPDIR)/autoX32-OMainWnd.Po
	-rm -f src/$(DEPDIR)/autoX32-OMainWndEvents.Po
	-rm -f src/$(DEPDIR)/autoX32-OMainWndUI.Po
	-rm -f src/$(DEPDIR)/autoX32-OOverView.Po
	-rm -f src/$(DEPDIR)/autoX32-OProject.Po
	-rm -f src/$(DEPDIR)/autoX32-OTimeDraw.Po
	-rm -f src/$(DEPDIR)/autoX32-OTimeView.Po
	-rm -f src/$(DEPDIR)/autoX32-OTrackDlg.Po
	-rm -f src/$(DEPDIR)/autoX32-OTrackDraw.Po
	-rm -f src/$(DEPDIR)/autoX32-OTrackEditDlg.Po
	-rm -f src/$(DEPDIR)/autoX32-OTrackStore.Po
	-rm -f src/$(DEPDIR)/autoX32-OTrackView.Po
	-rm -f src/$(DEPDIR)/autoX32-OTracksLayout.Po
	-rm -f src/$(DEPDIR)/autoX32-OX32.Po
	-rm -f src/$(DEPDIR)/autoX32-OscCmd.Po
	-rm -f src/$(DEPDIR)/autoX32-autoX32.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-dataDATA install-desktopDATA \
	install-dist_dataDATA install-pixmapsDATA

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
		-rm -f src/$(DEPDIR)/autoX32-OConnectDlg.Po
	-rm -f src/$(DEPDIR)/autoX32-ODAW.Po
	-rm -f src/$(DEPDIR)/autoX32-OMainWnd.Po
	-rm -f src/$(DEPDIR)/autoX32-OMainWndEvents.Po
	-rm -f src/$(DEPDIR)/autoX32-OMainWndUI.Po
	-rm -f src/$(DEPDIR)/autoX32-OOverView.Po
	-rm -f src/$(DEPDIR)/autoX32-OProject.Po
	-rm -f src/$(DEPDIR)/autoX32-OTimeDraw.Po
	-rm -f src/$(DEPDIR)/autoX32-OTimeView.Po
	-rm -f src/$(DEPDIR)/autoX32-OTrackDlg.Po
	-rm -f src/$(DEPDIR)/autoX32-OTrackDraw.Po
	-rm -f src/$(DEPDIR)/autoX32-OTrackEditDlg.Po
	-rm -f src/$(DEPDIR)/autoX32-OTrackStore.Po
	-rm -f src/$(DEPDIR)/autoX32-OTrackView.Po
	-rm -f src/$(DEPDIR)/autoX32-OTracksLayout.Po
	-rm -f src/$(DEPDIR)/autoX32-OX32.Po
	-rm -f src/$(DEPDIR)/autoX32-OscCmd.Po
	-rm -f src/$(DEPDIR)/autoX32-autoX32.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-dataDATA \
	uninstall-desktopDATA uninstall-dist_dataDATA \
	uninstall-pixmapsDATA

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles am--refresh check \
	check-am clean clean-binPROGRAMS clean-cscope clean-generic \
	cscope cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dataDATA install-desktopDATA \
	install-dist_dataDATA install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-pixmapsDATA install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS uninstall-dataDATA \
	uninstall-desktopDATA uninstall-dist_dataDATA \
	uninstall-pixmapsDATA

.PRECIOUS: Makefile


.PHONY : uninstall-gsettings-schemas install-gsettings-schemas clean-gsettings-schemas

mostlyclean-am: clean-gsettings-schemas

gsettings__enum_file = $(addsuffix .enums.xml,$(gsettings_ENUM_NAMESPACE))

%.gschema.valid: %.gschema.xml $(gsettings__enum_file)
	$(AM_V_GEN) $(GLIB_COMPILE_SCHEMAS) --strict --dry-run $(addprefix --schema-file=,$(gsettings__enum_file)) --schema-file=$< && mkdir -p $(@D) && touch $@

all-am: $(gsettings_SCHEMAS:.xml=.valid)
uninstall-am: uninstall-gsettings-schemas
install-data-am: install-gsettings-schemas

.SECONDARY: $(gsettings_SCHEMAS)

install-gsettings-schemas: $(gsettings_SCHEMAS) $(gsettings__enum_file)
	@$(NORMAL_INSTALL)
	if test -n "$^"; then \
		test -z "$(gsettingsschemadir)" || $(MKDIR_P) "$(DESTDIR)$(gsettingsschemadir)"; \
		$(INSTALL_DATA) $^ "$(DESTDIR)$(gsettingsschemadir)"; \
		test -n "$(GSETTINGS_DISABLE_SCHEMAS_COMPILE)$(DESTDIR)" || $(GLIB_COMPILE_SCHEMAS) $(gsettingsschemadir); \
	fi

uninstall-gsettings-schemas:
	@$(NORMAL_UNINSTALL)
	@list='$(gsettings_SCHEMAS) $(gsettings__enum_file)'; test -n "$(gsettingsschemadir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(gsettingsschemadir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(gsettingsschemadir)" && rm -f $$files
	test -n "$(GSETTINGS_DISABLE_SCHEMAS_COMPILE)$(DESTDIR)" || $(GLIB_COMPILE_SCHEMAS) $(gsettingsschemadir)

clean-gsettings-schemas:
	rm -f $(gsettings_SCHEMAS:.xml=.valid) $(gsettings__enum_file)

ifdef gsettings_ENUM_NAMESPACE
$(gsettings__enum_file): $(gsettings_ENUM_FILES)
	$(AM_V_GEN) glib-mkenums --comments '<!-- @comment@ -->' --fhead "<schemalist>" --vhead "  <@type@ id='$(gsettings_ENUM_NAMESPACE).@EnumName@'>" --vprod "    <value nick='@valuenick@' value='@valuenum@'/>" --vtail "  </@type@>" --ftail "</schemalist>" $^ > $@.tmp && mv $@.tmp $@
endif


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
