static char timeview_inline_glade[] = 
"<?xml version='1.0' encoding='UTF-8'?>"
"<!-- Generated with glade 3.39.0 -->"
"<interface>"
"  <requires lib='gtk+' version='3.20'/>"
"  <object class='GtkBox' id='time-box'>"
"    <property name='height-request'>30</property>"
"    <property name='visible'>True</property>"
"    <property name='can-focus'>False</property>"
"    <property name='valign'>start</property>"
"    <child>"
"      <!-- n-columns=3 n-rows=3 -->"
"      <object class='GtkGrid'>"
"        <property name='visible'>True</property>"
"        <property name='can-focus'>False</property>"
"        <child>"
"          <object class='GtkLabel' id='o-timecode'>"
"            <property name='width-request'>160</property>"
"            <property name='visible'>True</property>"
"            <property name='can-focus'>False</property>"
"          </object>"
"          <packing>"
"            <property name='left-attach'>0</property>"
"            <property name='top-attach'>0</property>"
"            <property name='width'>2</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class='GtkLabel' id='o-viewstart'>"
"            <property name='name'>ViewStart</property>"
"            <property name='visible'>True</property>"
"            <property name='can-focus'>False</property>"
"          </object>"
"          <packing>"
"            <property name='left-attach'>0</property>"
"            <property name='top-attach'>1</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class='GtkLabel' id='o-viewend'>"
"            <property name='name'>ViewEnd</property>"
"            <property name='visible'>True</property>"
"            <property name='can-focus'>False</property>"
"          </object>"
"          <packing>"
"            <property name='left-attach'>1</property>"
"            <property name='top-attach'>1</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <placeholder/>"
"        </child>"
"        <child>"
"          <placeholder/>"
"        </child>"
"        <child>"
"          <placeholder/>"
"        </child>"
"        <child>"
"          <placeholder/>"
"        </child>"
"        <child>"
"          <placeholder/>"
"        </child>"
"      </object>"
"      <packing>"
"        <property name='expand'>False</property>"
"        <property name='fill'>True</property>"
"        <property name='position'>0</property>"
"      </packing>"
"    </child>"
"    <child>"
"      <placeholder/>"
"    </child>"
"  </object>"
"</interface>"
;
