static char trackview_inline_glade[] = 
"<?xml version='1.0' encoding='UTF-8'?>"
"<!-- Generated with glade 3.22.2 -->"
"<interface>"
"  <requires lib='gtk+' version='3.20'/>"
"  <object class='GtkBox' id='track-box'>"
"    <property name='visible'>True</property>"
"    <property name='can_focus'>False</property>"
"    <property name='hexpand'>True</property>"
"    <property name='vexpand'>True</property>"
"    <child>"
"      <object class='GtkExpander' id='track-expander'>"
"        <property name='name'>track-expander</property>"
"        <property name='width_request'>160</property>"
"        <property name='visible'>True</property>"
"        <property name='can_focus'>True</property>"
"        <child>"
"          <object class='GtkBox' id='track-control'>"
"            <property name='name'>track_control</property>"
"            <property name='visible'>True</property>"
"            <property name='can_focus'>False</property>"
"            <property name='vexpand'>True</property>"
"            <property name='orientation'>vertical</property>"
"            <property name='baseline_position'>bottom</property>"
"            <child>"
"              <object class='GtkToolbar' id='track-bar'>"
"                <property name='name'>OMainToolbar</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='halign'>start</property>"
"                <property name='valign'>start</property>"
"                <child>"
"                  <object class='GtkToggleToolButton' id='track-rec'>"
"                    <property name='visible'>True</property>"
"                    <property name='can_focus'>False</property>"
"                    <property name='valign'>start</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>False</property>"
"                    <property name='homogeneous'>False</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class='GtkToggleToolButton' id='track-touch'>"
"                    <property name='visible'>True</property>"
"                    <property name='can_focus'>False</property>"
"                    <property name='valign'>start</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>False</property>"
"                    <property name='homogeneous'>False</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>False</property>"
"                <property name='position'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkBox' id='box-sizer'>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='orientation'>vertical</property>"
"                <child>"
"                  <placeholder/>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>1</property>"
"              </packing>"
"            </child>"
"          </object>"
"        </child>"
"        <child type='label'>"
"          <object class='GtkLabel' id='track-label'>"
"            <property name='visible'>True</property>"
"            <property name='can_focus'>False</property>"
"            <property name='label' translatable='yes'>expander</property>"
"          </object>"
"        </child>"
"      </object>"
"      <packing>"
"        <property name='expand'>False</property>"
"        <property name='fill'>True</property>"
"        <property name='position'>0</property>"
"      </packing>"
"    </child>"
"    <child>"
"      <placeholder/>"
"    </child>"
"  </object>"
"</interface>"
;
