static char trackdlg_inline_glade[] = 
"<?xml version='1.0' encoding='UTF-8'?>"
"<!-- Generated with glade 3.39.0 -->"
"<interface>"
"  <requires lib='gtk+' version='3.20'/>"
"  <object class='GtkDialog' id='track-dlg'>"
"    <property name='can-focus'>False</property>"
"    <property name='type-hint'>dialog</property>"
"    <child internal-child='vbox'>"
"      <object class='GtkBox'>"
"        <property name='can-focus'>False</property>"
"        <property name='orientation'>vertical</property>"
"        <property name='spacing'>2</property>"
"        <child internal-child='action_area'>"
"          <object class='GtkButtonBox'>"
"            <property name='can-focus'>False</property>"
"            <property name='layout-style'>end</property>"
"            <child>"
"              <object class='GtkButton' id='btn-cancel'>"
"                <property name='label' translatable='yes'>Cancel</property>"
"                <property name='visible'>True</property>"
"                <property name='can-focus'>True</property>"
"                <property name='receives-default'>True</property>"
"              </object>"
"              <packing>"
"                <property name='expand'>True</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkButton' id='btn-ok'>"
"                <property name='label' translatable='yes'>Ok</property>"
"                <property name='visible'>True</property>"
"                <property name='can-focus'>True</property>"
"                <property name='receives-default'>True</property>"
"              </object>"
"              <packing>"
"                <property name='expand'>True</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name='expand'>False</property>"
"            <property name='fill'>False</property>"
"            <property name='position'>0</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class='GtkBox'>"
"            <property name='visible'>True</property>"
"            <property name='can-focus'>False</property>"
"            <property name='orientation'>vertical</property>"
"            <child>"
"              <object class='GtkBox' id='bx-name'>"
"                <property name='visible'>True</property>"
"                <property name='can-focus'>False</property>"
"                <property name='margin-start'>16</property>"
"                <property name='margin-end'>16</property>"
"                <property name='margin-top'>10</property>"
"                <property name='margin-bottom'>10</property>"
"                <child>"
"                  <object class='GtkLabel'>"
"                    <property name='visible'>True</property>"
"                    <property name='can-focus'>False</property>"
"                    <property name='halign'>start</property>"
"                    <property name='xpad'>8</property>"
"                    <property name='label' translatable='yes'>Track name:</property>"
"                    <property name='ellipsize'>start</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>True</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class='GtkEntry' id='txt-name'>"
"                    <property name='visible'>True</property>"
"                    <property name='can-focus'>True</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>False</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkBox' id='bx-name1'>"
"                <property name='visible'>True</property>"
"                <property name='can-focus'>False</property>"
"                <property name='margin-start'>16</property>"
"                <property name='margin-end'>16</property>"
"                <property name='margin-top'>10</property>"
"                <property name='margin-bottom'>10</property>"
"                <child>"
"                  <object class='GtkLabel' id='lbl-path'>"
"                    <property name='visible'>True</property>"
"                    <property name='can-focus'>False</property>"
"                    <property name='halign'>start</property>"
"                    <property name='xpad'>8</property>"
"                    <property name='label' translatable='yes'>Track path:</property>"
"                    <property name='ellipsize'>start</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>True</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class='GtkEntry' id='txt-path'>"
"                    <property name='visible'>True</property>"
"                    <property name='can-focus'>True</property>"
"                    <property name='editable'>False</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>False</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkBox' id='bx-name2'>"
"                <property name='visible'>True</property>"
"                <property name='can-focus'>False</property>"
"                <property name='margin-start'>16</property>"
"                <property name='margin-end'>16</property>"
"                <property name='margin-top'>10</property>"
"                <property name='margin-bottom'>10</property>"
"                <child>"
"                  <object class='GtkLabel' id='lbl-path1'>"
"                    <property name='visible'>True</property>"
"                    <property name='can-focus'>False</property>"
"                    <property name='halign'>start</property>"
"                    <property name='xpad'>8</property>"
"                    <property name='label' translatable='yes'>Track color:</property>"
"                    <property name='ellipsize'>start</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>True</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class='GtkColorButton' id='btn-color'>"
"                    <property name='visible'>True</property>"
"                    <property name='can-focus'>True</property>"
"                    <property name='receives-default'>True</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>False</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>2</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkBox'>"
"                <property name='visible'>True</property>"
"                <property name='can-focus'>False</property>"
"                <property name='margin-start'>20</property>"
"                <property name='margin-end'>20</property>"
"                <property name='margin-top'>20</property>"
"                <property name='margin-bottom'>20</property>"
"                <child>"
"                  <object class='GtkLabel'>"
"                    <property name='visible'>True</property>"
"                    <property name='can-focus'>False</property>"
"                    <property name='label' translatable='yes'>Count entries:</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>True</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class='GtkLabel' id='lbl-count-entries'>"
"                    <property name='visible'>True</property>"
"                    <property name='can-focus'>False</property>"
"                  </object>"
"                  <packing>"
"                    <property name='expand'>True</property>"
"                    <property name='fill'>True</property>"
"                    <property name='position'>1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>3</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name='expand'>False</property>"
"            <property name='fill'>True</property>"
"            <property name='position'>1</property>"
"          </packing>"
"        </child>"
"      </object>"
"    </child>"
"  </object>"
"</interface>"
;
